### ISSUE TITLE
希望能够支持开黑啦

### ISSUE THREAD

**Issue by ghost** [fossifer/LilyWhiteBot#2]
希望可以支持与开黑啦进行互通

**Comment by fossifer** [comment]
抱歉，目前精力有限，仅维护现有平台，还没有增加其他平台的计划。

**Comment by fossifer** [comment]
也可以试试[这个框架](https://github.com/koishijs/koishi)，看起来功能比较完备。

**Comment by ghost** [comment]
我看了下，貌似没有IRC的，不过可以考虑一下（我也有Discord）
